# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('titulo', models.CharField(blank=True, max_length=64, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=140, null=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('imagen', models.ImageField(blank=True, default='imagenes/default.png', null=True, upload_to='imagenes/empleados', verbose_name='Imagen Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.Categoria'),
        ),
    ]
