# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20170228_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/banners', verbose_name='Imagen Banner'),
        ),
    ]
