# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_auto_20170227_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vigencia', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='imagnes/comunicado', verbose_name='Imagen Comunicado')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/comunicado', verbose_name='Archivo Comunicado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado')),
            ],
        ),
    ]
