# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(blank=True, default='imagenes/default.png', null=True, upload_to='imagenes/empleados', verbose_name='Imagen Empleado'),
        ),
    ]
