# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_auto_20170227_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comisiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vigencia', models.DateTimeField(blank=True, null=True)),
                ('comision', models.CharField(max_length=10)),
                ('venta_minima', models.DecimalField(decimal_places=2, max_digits=12)),
                ('venta_maxima', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_Comisiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado')),
            ],
        ),
        migrations.AddField(
            model_name='comisiones',
            name='tabla_comisiones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comisiones.Tabla_Comisiones'),
        ),
    ]
