# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comisiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla_comisiones',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
